### ISSUE TITLE
Travis build broken due to missing jdk dependencies

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#120]
[Travis stopped building](https://travis-ci.org/Col-E/Recaf/builds/517130522) out of the blue a few days ago. It stopped working after this commit: 35aece63e6f083f342c9f2f9857d79e618619599

Yet, it complains about [another file entirely _(FxAttach)_](https://github.com/Col-E/Recaf/blob/master/src/me/coley/recaf/ui/FxAttach.java), because the following classes can't be found:

* `VirtualMachineDescriptor`
* `VirtualMachine`

That file hasn't been touched since March 10th. Travis stopped building because of it yesterday, April 8th.

It looks like the `com.sun.tools.attach` package is no longer is loaded by Travis... I'm going to assume it no longer loads `tools.jar` into the classpath for compilation. I'm not sure how to fix this since doing nothing resulted in it failing.

**Comment by IwoTens** [comment]
Hey, 

I'm reasonably certain the problem started with the following [commit](https://github.com/Col-E/Recaf/commit/1db872cbf36c503cbbd0abcab0e87b2a228d7421). 
Previously the 1.0 version of the memory compiler was used, which had the tools.jar listed as a dependency in the pom file. In 2.0 this was removed. Since it does not seem to be needed in the memory compiler, it probably should not be readded to it again.

My search led me to the [following solution](https://stackoverflow.com/a/52265162/1255165). This seems to work very well. In addition to fixing the imports in Jdk8 it also seem to interact nicely with Jdk9+.

**Comment by Col-E** [comment]
Oh no, you're probably very much correct. I'm just an idiot :rofl:

**Comment by Col-E** [comment]
Yup, it builds now :upside_down_face: 

Thanks for the quick catch!
