### ISSUE TITLE
ALOAD 0 instead of ALOAD THIS

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#137]
While opening the code in Assembler shows me ALOAD 0 instead of ALOAD THIS, and after saving this code the decompiler gets weird, but on runtime this seems to work.

Example:
Function in assembler:
`ALOAD 0
FLOAD 1
INVOKEVIRTUAL com/desertkun/brainout/AuX/aux/jh.setX(F)V
ALOAD 0
FLOAD 2
INVOKEVIRTUAL com/desertkun/brainout/AuX/aux/jh.setY(F)V
RETURN `

Function in decompiler:
`public void setPosition(float f2, float f3) {
    this.setX(f2);
    this.setY(f3);
}`

Function after saving:
`public void setPosition(float f2, float f3) {
    jh jh2;
    jh2.setX(f2);
    jh2.setY(f3);
}`

**To Reproduce**
1. Open any function that uses 'this'
2. Open it in assembler
3. (You can just press space at the end of file) change something 
4. Save and decompile

**Comment by Col-E** [comment]
If `ALOAD 0` is being emitted, then the local variable debug table does not have the name for the 0th variable set to `this`. However since this is a common case I'll add a condition to make sure `this` is used.

**Note**: `ALOAD 0` and `ALOAD this` _(`this` is all lower-case)_ are the same if the method is _not static_. 

**Note**: When sharing multi-line code snippets you can use the following for better formatting: _(Remove that first `\` shown below)_
```
\```
code
with
lines
\```
```

**Comment by Col-E** [comment]
Labeling `enhancement` for since this behavior of `0` vs `this` isn't a bug.
Labeling `bug` because of the wrong decompilation, which is likely caused by the fact that the assembler isn't properly regenerating the type of `this` in the local variable table after the assembly is saved.
