### ISSUE TITLE
Embed java code into Assembler

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#145]
## Embed java code into Assembler

I want for an example embed code like `boolean x = true;` right in assembler, with java bytecode. Or, i just want to see, how will this be in java bytecode, like 
`int var = 0;` 
is 
```
ICONST_0
ASTORE var
```

**Comment by Col-E** [comment]
Mixing two different syntax styles is something I'm not going to support. The assembler is designed to be an alternative to the instructions list editor. For editing using java code you can use the class decompiler window, make your changes, then save them.

**Comment by artemking4-Projects** [comment]
Ok, then the recompiler doesnt support var/function names like do/for/while

**Comment by artemking4-Projects** [comment]
that i really have

**Comment by Col-E** [comment]
> the recompiler doesnt support var/function names like do/for/while

The recompiler uses `javac` and isn't intended to be used with obfuscated code. It's a nice utility when working with cleaner and simpler code. 

When working with obfuscated code there are two primary paths to take:

* Deobfuscate the obfuscated code so that it is easier to work with, then use the nice utilities _(Renaming can be done in Recaf, but for large-scale renaming I would recommend specialized tools such as [JRemapper](https://github.com/Col-E/JRemapper))_
* Use lower level editor functions _(Like the instructions list window, or the assembler)_

**Comment by artemking4-Projects** [comment]
Ok, i iwll now try doing something with jremapper

**Comment by artemking4-Projects** [comment]
new issue at JRemapper
