### ISSUE TITLE
Improved Search Result Window

### ISSUE THREAD

**Issue by Dj-jom2x** [Col-E/Recaf#167]
## Search reference on search reference result. + Allow to decompile it

Short description of the feature
Allow searching reference on reference result and beyond.
Allow decompiling not just bytecode. on reference when you right click it
***

**Extra details**:
no more just read verbose..

* More verbose details of features

because when we search the menu context at right click is so limited. we cant perform more reference .. example if I search a reference.. then reference show. I wanted to right-click that and search for reference.. instead of finding the class and manually click the search reference there.. also allow to decompile not just assembly.

**Comment by Col-E** [comment]
So to clarify, you want to be able to see the references to the references from a search? 

This sounds a lot like how **dnSpy** does their searching:
![image](https://user-images.githubusercontent.com/21371686/64145207-c7838180-cde5-11e9-8eca-f62ff37f7926.png)

***

As for the decompilation instead of the bytecode do you mean like this?

* Search for a reference to XYZ
* Shows result from ABC
* Right clicking result decompiles ABC

**Comment by Dj-jom2x** [comment]
yes yes.. like dnspy :) I use that too.  I also look for similar dnspy like but in java.. and I found yours... 👍

**Comment by Col-E** [comment]
Currently I'm not looking to add to the `1.X` branch but for when `2.X` is out I'll look to add this :+1:

**Comment by Col-E** [comment]
Added in: 6671f78b1bf2ac836202189d71527b403c4f3a33

![2020-03-06_15-16-53-converted](https://user-images.githubusercontent.com/21371686/76119620-d2e67e00-5fbd-11ea-88a6-5bc1a8e32b72.gif)

While it's not _literally_ the same as DnSpy, the same functionality is now supported in `2.X`. I may add reference search to specific instruction types in the search window as well _(class/field/method references)_

I chose not to copy DnSpy's layout exactly because it didn't align well with the architecture of how the UI was designed in Recaf. I'm open to PR's if anyone's up to the challenge though.
