### ISSUE TITLE
Recaf 2.0.0 disassembler errors LSTORE

### ISSUE THREAD

**Issue by Ilolka1337** [Col-E/Recaf#194]
LSTORE displays error in disassembler 
this only happens with some types of LSTORE

Screenshots:
![image](https://user-images.githubusercontent.com/63341162/78961955-cba21b00-7afb-11ea-9adc-9649ed7b2eb1.png)
![image](https://user-images.githubusercontent.com/63341162/78962131-52ef8e80-7afc-11ea-9aee-a409c486349c.png)
![image](https://user-images.githubusercontent.com/63341162/78962143-5daa2380-7afc-11ea-8dfd-574acb4f62a8.png)

**Comment by Col-E** [comment]
This actually is not a error with the `LSTORE` instruction. As the error in the log section states it cannot find starting labels for these variables. 

Variable information is a debug-only attribute. It serves no real functional purpose. In Recaf, I attempt to re-create these variables when you edit them so that you do have this extra information. Variables require a start and end range. In these case, there is no valid start identifier _(a label)_ before the first `LSTORE` so Recaf gets confused. 

As for why there is not a label at the start, [that's something ASM handles](https://gitlab.ow2.org/asm/asm/-/blob/master/asm/src/main/java/org/objectweb/asm/ClassReader.java#L1508). It doesn't seem to recognize that there needs to be a label near the start for these methods. Not exactly sure why.

**Solutions**:

1. Add a label definition before the instruction that complains there is no start label.
2. I can add the option to not re-create variable information. So this extra parsing step will get skipped.

**Comment by Col-E** [comment]
Closing for now since this _seems_ to be an issue with ASM not inserting labels in all the right places for this obfuscated sample.
