### ISSUE TITLE
allow infinite decompile time

### ISSUE THREAD

**Issue by ThatGamerBlue** [Col-E/Recaf#232]
## Infinite Decompile Time

Would be nice to allow infinite decompile time, as some classes can be rather large when reverse engineering and 20 seconds isn't long enough.

**Comment by Col-E** [comment]
Temporarily if you want to bypass this, open the Recaf config directory, then edit `decompiler.json` and set `timeout` to some absurdly high value. `1000` is one second for reference.

I've never had a class that took longer than 20 seconds, assuming it wasn't an intentional crash targeting the decompiler.
Perhaps you could try running it through a deobfuscator tool first to try and clear our some junk?

**Comment by ThatGamerBlue** [comment]
Thanks for the bypass. The class in question has already been run through a deobber and decompiles back to compile-able equivalent source code. Due to the nature of the class in question I can't upload it here, however I can tell you it is 919,335 bytes in size, has 355 fields and 1054 methods.

**Comment by Col-E** [comment]
> 919,335 bytes in size, has 355 fields and 1054 methods. 

:astonished:

**Comment by Crystallinqq** [comment]
that class is off the perc 10

**Comment by Col-E** [comment]
3X will have the explicit option to disable the timeout

**Comment by Alexandros444** [comment]
Where is the decompiler.json in the jar version? I only have the jar executable.
Should i download another version?

**Comment by Amejonah1200** [comment]
Use https://github.com/Col-E/Recaf-Launcher to get 4.x
