### ISSUE TITLE
How to ignore errors.

### ISSUE THREAD

**Issue by iBikky** [Col-E/Recaf#351]
How can I ignore errors like this and just export it? 
![Screen Shot 2021-02-09 at 3 44 23 pm](https://user-images.githubusercontent.com/65581364/107316928-c2078c00-6aed-11eb-8724-75efd479c59e.png)
When i change stuff and load it again it won't save the changes.

**Comment by Col-E** [comment]
These errors cannot be ignored.

If you are attempting to recompile your changes and you see an error like this its because is not being fed the all the references it needs. You are always encouraged to use the assembler to make changes that cannot be done via the compiler.

Under `Config > Assembler` do you have `Generate missing classes` enabled?

**Comment by iBikky** [comment]
yes I have it enabled

**Comment by Col-E** [comment]
Can you check the logs and see if the class generation failed?

Help > System Information > Open Recaf Directory

Should be `rclog.txt`

**Comment by iBikky** [comment]
[rclog.txt](https://github.com/Col-E/Recaf/files/5950346/rclog.txt)

**Comment by Col-E** [comment]
>the entire log is spamming invalid class because the jar has MacOS artifacts
🤢 

Whoever packaged this jar ought to learn how to do packaging properly. Anyways, delete the `__MACOSX` directory and retry so the logs aren't so cluttered with garbage. I can't tell if anything important is happening due to the spam.

**Comment by iBikky** [comment]
where is that directory located?

**Comment by Col-E** [comment]
Its in the jar file itself
