### ISSUE TITLE
Saving to a network location takes a very long time

### ISSUE THREAD

**Issue by gesture1968** [Col-E/Recaf#391]
When saving to a Windows network shared drive, it takes a very long time (a 2K file took at least 5 minutes). Saving locally is almost instantly

**Comment by Col-E** [comment]
Note on improvement: Write file output to temp _(can use recaf dir so the file doesn't get lost if something breaks)_ file, then move it to the target location vs saving directly to location. See: <https://forum.image.sc/t/slow-tiff-writing-performance-on-network-drives-from-windows/30100/4>

**Comment by gesture1968** [comment]
Thanks, indeed I already use that workaround. But calling a filesize of 2K a big file? And why should there be a lot of small writes, the file structure can be easily build in memory before it is written to file... I still feel there is something not entirely correct in the way the file is written

**Comment by Col-E** [comment]
> Big file

I'm speaking in general terms. But that being said, my experience with network shares is best described as ***"ＰＡＩＮ"*** so my expectations of speed are very low. 

> And why should there be a lot of small writes, the file structure can be easily build in memory before it is written to file

This is generally is the case, it was just [implemented on top of file streams in the first place](https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/command/impl/Export.java#L128) and there's not been any reason to change it since up until now nobody has opened an issue regarding potential performance loss.

But its an easy fix.

**Comment by gesture1968** [comment]
_But its an easy fix_

That would be great!

**Comment by Col-E** [comment]
Will be in the next release
