### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by mrparag94** [Col-E/Recaf#395]
I am having this problem.. how I can solve it...?

![image](https://user-images.githubusercontent.com/72906386/125150543-6572d080-e162-11eb-86f9-516bc9144f7c.png)

**Comment by Col-E** [comment]
Errors like this occur when the decompiler failed to create parsable Java code. This prevents right-click context menus from working since there isn't a way to figure out what you're clicking on. However this only applies to decompile mode. You can switch to table mode to bypass the need for valid decompilation.

More info: https://www.coley.software/Recaf-documentation/use-modes.html
