### ISSUE TITLE
No green flash when pressing save keybind

### ISSUE THREAD

**Issue by TheGloriousDuck** [Col-E/Recaf#428]
**Describe the bug**

> There is no green flash when I press CTRL+S. I tried changing it to other keybinds as well, but it still didn't work.

**To Reproduce**

1. Open any sample jar (cannot provide the one I am using)
2. Navigate to any class
3. Change anything in the file and save
4. No green flash occurs

There are no errors in the cmd. 
![image](https://user-images.githubusercontent.com/43049985/143779374-1d83c9d5-9608-4cef-9e70-63eb78dbfcf4.png)

**Comment by win32kbase** [comment]
Err.. this does not occur with any sample. Going to need one to reproduce.

**Comment by TheGloriousDuck** [comment]
Sorry, by sample jar I meant just a random jar. I used a random jar I had with just 2 classes and it worked fine... But not working on the jar that I am trying to modify now (cannot send it). It has 7555 classes and 4052 files, could that be the issue? I am also using Procyon as the decompiler because the other decompilers fail to decompile.

**Comment by win32kbase** [comment]
The recompilation process is probably failing. I'm assuming the jar you're attempting to edit is obfuscated in some way. Generally obfuscated JARs cannot be recompiled due to the fact that they don't decompile into recompileable code. You will probably have to edit using the assembler:

https://www.coley.software/Recaf-documentation/use-assembler.html

**Comment by TheGloriousDuck** [comment]
It is obfuscated.. Thanks for the link though! I'll check it out

**Comment by TheGloriousDuck** [comment]
I was able to do what I needed using the assembler and EXPR! Thank you.
