### ISSUE TITLE
Add a checkbox to hide try catches

### ISSUE THREAD

**Issue by 3jq** [Col-E/Recaf#453]
## Hide Try Catches

Add a checkbox to hide try catches while inspecting decompiled code/bytecode

**Comment by win32kbase** [comment]
Why?

**Comment by Col-E** [comment]
Its a feature that ThreadTear offers because of some _intentional_ flow obfuscation with try-catches that crash decompilers. But the problem is then the output is very far from being logically correct so its rather deceiving for most users who turn the option on. 

I don't plan on adding something like that, rather the correct approach would be a proper transformer addressing the obfuscation.

**Comment by 3jq** [comment]
Uhh, that would be very good in case of code not getting decompiled because of try catches.

**Comment by win32kbase** [comment]
> the correct approach would be a proper transformer addressing the obfuscation.

Col-E is right, the editor should not be responsible for removing obfuscation
