### ISSUE TITLE
Copy method

### ISSUE THREAD

**Issue by JhonImmanuel** [Col-E/Recaf#46]
How to copy method on recaf?

Let assume I had method called setBeeperVolume and I want to copy method to setBeeperVolume2.
is it possible to do?

![image](https://user-images.githubusercontent.com/7777519/38594432-6491a298-3d70-11e8-8229-f4f4f8b86693.png)

Thanks

**Comment by Col-E** [comment]
So right now, you can't do it directly. I'm currently [rewriting](https://github.com/Col-E/Recaf/issues/45) recaf and will put this on the todo list. When its ready to be used I'll push the code, but thats a bit aways. I'm not going to continue working with this code-base since the rewrite is my primary focus.

In the meantime, you can use the opcode-block feature to copy over opcodes *(Excluding invokedynamic)* to copy over opcodes manually.

* Make a new method
* Open the original method, select all opcodes
* Save as opcode-block
* Open new method
* Insert opcode-block

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/commit/e3142a1a807064f263001b7f8a03d15607821bdd
