### ISSUE TITLE
Please include some kind of highlighter sync between decompiler and bytecode. 

### ISSUE THREAD

**Issue by Redcode456123** [Col-E/Recaf#47]
A highlighter synched between Decompiler and Bytecode  Editor is great help.
Could you implemented ?

Thanks.

**Comment by Col-E** [comment]
This would be kinda complicated to add with how I use CFR *(the decompiler)*. I imagine it can be done but I'd have to do a lot of diving through undocumented code.

So possibly in the future, but I can't give you an estimate right now on how long it would take.

**Comment by FFY00** [comment]
I mean, if you have the line opcodes, that would be easy. That would only work for non-obfuscated code as the obfuscators remove them.

**Comment by Col-E** [comment]
Realistically even if you remove them you can use the stack-frames to fill in most of the gaps. I was initially thinking that it would be ideal to have access to the AST of some decompiled code so that you could match what it represents to the text of the decompiled code. 

The decompiler I use is CFR, and it is currently [not posting its source](http://www.benf.org/other/cfr/faq.html).  So I would have to skim through the decompiled lib to do the approach I was thinking of. I know there are other libraries, but I've liked the consistency of CFR even with obfuscated inputs.

**Comment by Col-E** [comment]
While this would be very useful _(and is present in the recently releases NSA tool Ghidra)_ the decompiler I use does not have the functionality to allow for this to be implemented. This isn't to say other decompilers _do have these features_. I'm not aware of any that would allow such functionality. 

Down the road, I could potentially write a decompiler/disassembler that does this to _some degree_ as an alternative to a straight decompile.
