### ISSUE TITLE
About adding, modifying and deleting annotations.

### ISSUE THREAD

**Issue by ImFl0wow** [Col-E/Recaf#479]
## About adding, modifying and deleting annotations

I found that Recaf has no feature about modifying annotations.
Why not add it?

**Comment by Col-E** [comment]
This is something that will be supported in the 3X release. It's been added to the bytecode parser grammer: https://github.com/Col-E/Recaf/blob/dev3/recaf-assembler/src/main/antlr/me/coley/recaf/assemble/parser/Bytecode.g4#L139

The assembler supports editing fields and methods, editing class level definitions is all that remains in order to fully support annotation editing in 3X. It shouldn't be too hard to tweak the grammar to also support class definitions, most of the work will probably be in UI integrations. But it will be something that will get done.

**Comment by ImFl0wow** [comment]
LEF's 邮箱自动回复：请留下您的QQ，然后说清要办的事情我会定期查看邮箱。QQ1720766910--------------------------LEF-gangaDev 2018/12/26设置

**Comment by Col-E** [comment]
Closing as 4.X is the only branch we're working on going forward. The assembler is capable of adding/removing annotations now.

For instance here's a class with an annotation:
```js
.annotation TestAnnotation {
    number: 15,
    bogusNumber: NaN,
    charValue: 'c',
    subWithString: .annotation org/jetbrains/annotations/NotNull {
        value: "Hello, world!"
    },
    subWithEnum: .annotation EnumHolder {
        value: .enum net/fabricmc/api/EnvType CLIENT
    },
    subWithClass: .annotation ClassHolder {
        value: { java/lang/String }
    },
    stringArray: { "one", "two", "three" }
}
.super java/lang/Object
.class public super Example {

}
```
```java
@TestAnnotation(
  number = 15,
  bogusNumber = NaN,
  subWithString = @NotNull("Hello world"),
  subWithEnum = @EnumHolder(EvnType.CLIENT),
  subWithClass = @ClassHolder(String.class),
  stringArray = [ "one", "two", "three" ]
)
public class Example {}
```
