### ISSUE TITLE
Update Fernflower decompiler

### ISSUE THREAD

**Issue by Fox2Code** [Col-E/Recaf#489]
## Update fernflower decompiler

The current version of FernFlower shipped with Recaf doesn't support Java17

I Would like it to be updated if possible. Or if not use a fork of it like QuiltFlower.

CFR still work correctly for Java17, but I know Fernflower and it's forks are more accurate.

**Comment by Col-E** [comment]
I've been peeking at the quilt fork every now and then. Certainly looks nice and I hope to see more enhancements put into it. 

Currently in 2X we're using the forge fork since its the first easy artifact I found: https://github.com/Col-E/Recaf/blob/master/pom.xml#L128

If you could find an artifact host of a more up to date version I or anyone could open a PR to update it.

> but I know Fernflower and it's forks are more accurate.

![image](https://user-images.githubusercontent.com/21371686/153889233-3923a2bb-64b2-4f67-af42-155011129b05.png)

CFR is giga-chad software.

**Comment by tth05** [comment]
The QuiltFlower decompiler is hosted here https://maven.quiltmc.org/repository/snapshot/org/quiltmc/quiltflower/

**Comment by faastcall** [comment]
Recaf should ideally use upstream fernflower, not some fork.

**Comment by PhoenixVX** [comment]
Recaf already uses ForgeFlower, due to original Fernflower not being provided on a Maven.
