### ISSUE TITLE
Exception: java.io.FileNotFoundException on Kali Linux armhf

### ISSUE THREAD

**Issue by KhanhNguyen9872** [Col-E/Recaf#512]
OS: Linux
Version: 17.0.2
Vendor: Debian

Exception: java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-linux-arm32.jar
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLocalDependencies(SelfDependencyPatcher.java:76)
	at me.coley.recaf.util.self.SelfDependencyPatcher.ensureJavafxSupport(SelfDependencyPatcher.java:53)
	at me.coley.recaf.Recaf.init(Recaf.java:84)
	at me.coley.recaf.Recaf.main(Recaf.java:51)

**Comment by KhanhNguyen9872** [comment]
![Screenshot_20220326-211959.png](https://user-images.githubusercontent.com/88880309/160243722-4030d458-5e6a-4416-bd70-7f544f078275.png)

**Comment by win32kbase** [comment]
Looking at the repo (https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+3/) it seems only monocle jars are available for arm32.

**Comment by KhanhNguyen9872** [comment]
> Looking at the repo (https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+3/) it seems only monocle jars are available for arm32.

so it can't use recaf right?

**Comment by win32kbase** [comment]
It appears so, unless @Col-E has a comment on it

**Comment by Col-E** [comment]
Like @win32kbase said it seems the target for arm32 is only [Monocle](https://wiki.openjdk.java.net/display/OpenJFX/Monocle) which I'm not sure is what your system needs. Plus the monocle artifacts do not have native bindings for everything since they're intended for embedded systems. Additionally I do not think the _"default"_ artifact (https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+3/javafx-media-18-ea+3-linux.jar) is also what your system needs because the natives in that one are compiled against x86, not ARM.

The code responsible for determining the JavaFX natives to pull is here: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/util/self/SelfDependencyPatcher.java#L257

-----------

You can attempt to use a JDK such as https://bell-sw.com/pages/downloads/ that bundles JavaFX internally. Bellsoft has multiple versions to choose from on their download page. The _"Full"_ option should include JFX. I'm not sure if they have their own natives for platforms not officially up on maven central.
