### ISSUE TITLE
cpu usage increasing to 99.9% with recaf 3

### ISSUE THREAD

**Issue by darklol9** [Col-E/Recaf#541]
**Describe the bug**

> When I virtualize or optimize (not 100% sure this causes it) the CPU usage of the application will increase by like 10% and stay there, an example being before I do anything it is 8% and after reaches 20% average and would keep increasing every time I did it

**To Reproduce**

1. Open Sample
2. Open class
3. Right click on method name and run it using ssvm

**Screenshots**
![image](https://user-images.githubusercontent.com/75024786/170789060-ef99935d-dddb-4267-8718-ff45138c719a.png)
CPU usage after trying to run a method a couple times, was originally around 8 but rose to 30 and didn't go back down

**Comment by darklol9** [comment]
I realised it wasn't ssvm but recaf itself, after a few mins of using it becomes unusable and cpu is at 99%

**Comment by Col-E** [comment]
> but recaf itself

I can't seem to reproduce this. Recaf 3X for me usually goes back down to ~10% usage idle. Here's a graph of CPU usage:
![image](https://user-images.githubusercontent.com/21371686/173272763-b06fc859-f75b-4ee9-9dfe-0e3c389430d2.png)

**Comment by Col-E** [comment]
Try the newest release out: https://github.com/Col-E/recaf-3x-issues/releases/tag/3.0.0-SNAPSHOT-13

Specifically, [this commit](https://github.com/Col-E/Recaf/commit/59c3afb1e80a3b244055540cac61c128bc064f16) should fix these higher than expected idle percentages. Root cause was a damn progress bar I added to make the decompile waiting screen look nicer... 💢 - https://bugs.openjdk.org/browse/JDK-8200239

New CPU chart:
![image](https://user-images.githubusercontent.com/21371686/177000832-9c4550d5-1c76-4ce0-9f3a-932e76a9221a.png)

Spikes are only around when a larger class is being decompiled.

**Comment by darklol9** [comment]
Thanks this is a lot better
