### ISSUE TITLE
Unable to open the right-click context menu of methods in one specific class.

### ISSUE THREAD

**Issue by Alluseri** [Col-E/Recaf#558]
**Describe the bug**
When right clicking on methods in a specific class(see the reproduction section), the context menu doesn't appear and an exception is thrown instead.

**To Reproduce**

1. Open [sample](https://github.com/Hqrion-Clientz/Phobos-1.9.0-BUILDABLE-SRC/releases/download/1.9.0/Phobos-1.9.0-Release.jar)
2. Navigate to `me/earth/phobos/mixin/mixins/MixinRenderLivingBase`
3. Right click on any of the given methods(ctor, renderModelHook, doRenderPre and doRenderPost)
4. See error in log, context menu won't appear.

**Exception**
[See here, it's pretty large and I want to keep the issue clean](https://pastebin.com/crCyFXCc)

**Screenshots**
<img src="https://cdn.discordapp.com/attachments/853155168170147910/995514852359536671/explorer_91b0l4EThh.gif">
(The stacktrace was spammed so many times because I spammed right-click, it's actually one exception per click.)

**Comment by Col-E** [comment]
Will take a look when I'm available. Though since I'm curious, does it work in the 3X  snapshots / dev branch?

**Comment by Alluseri** [comment]
`07:38:05.387 [JavaArea:WARN] No recognized class or member at selected position [line 35, column 26]` when I click anywhere inside methods, if I click right on the name of the method it opens the context menu for the class instead. Do you need a reproduction .gif?

**Comment by Col-E** [comment]
Sure. Anyways like I said I'll take a look at the sample when I'm available

**Comment by Col-E** [comment]
Also somewhat related:
`02:37:01.855 [JavaParserResolving/JavaFX Application Thread] WARN : Cannot map resolved item 'MixinRenderLivingBase' to workspace class/member info due to unsolved symbol: RenderManager`

If you see a message like this, that means Phantom classes weren't generated, so JavaParser does not have access to the type information it needs to ensure a proper match. So if you had a method that has `RenderManager` as an argument, it wouldn't be able to make the match for that method, even if the type is listed as an import in the decompiled code. Its largely based on what is available in the workspace for this case.

**Comment by Alluseri** [comment]
OT, does your Phantom class generation not feature generating classes with generics? I'd figure it would be an easy task to do, especially if the generic type specification is known(e.g. in another type declaration)

**Comment by Alluseri** [comment]
Alright, I'll try dealing with it if I manage to setup the whole project correctly. (Don't) expect a PR regarding that from me in the next 5 years. Cheers!

**Comment by Col-E** [comment]
Cheers 🍻
