### ISSUE TITLE
/*  * Duplicate member names - consider using --renamedupmembers true  */

### ISSUE THREAD

**Issue by ParityError** [Col-E/Recaf#563]
**Describe the bug**

While decompiling with Recaf with CFR I get a message in the decompiled code that says:
```
/*
 * Duplicate member names - consider using --renamedupmembers true
 */
````
the edit file will not save or recompile.  (there are also lots of other errors)

**To Reproduce**

Decompile any obfuscated .jar and you'll likely encounter this message.

**Exception**
```
Thread] WARN : Line 206, Col 16: reference to e is ambiguous
  both method e() in p and method e() in p match
ERROR: Failed recompiling code for 'ClassMember' - Reason: 'Failed compile due to compilation errors'
```
Is there some way to include the `--ranamedupmembers` in the options while using `Recaf` with CFR? Or any tips for dealing with obfuscated .Jar files? Thanks.

**Comment by Col-E** [comment]
You are extremely unlikely to successfully recompile obfuscated code. `javac` does not let you have two fields/methods of the same name _(even if they have different parameters/types)_. The assembler is your friend, use it 👍 

Anyways, CFR has a feature that lets you rename things that have the same. Cool. But imagine you have a class that implements the following obfuscated interface:
```java
interface a {
    void a();
    void a(int a);
    boolean a();
}
```
If you rename the overridden methods with duplicate names from the interface then `javac` will complain you have not implemented all of the methods. Yet, you can't possibly do so because of the restriction mentioned before. 

You can use the mapping feature to rename the base interface methods _(and thus all of the implementations of that through the program)_ so that they are no longer all using the same duplicate name. But if you only need to make simple changes I highly recommend sticking with the assembler.
