### ISSUE TITLE
[Question] Can i edit class constructor?

### ISSUE THREAD

**Issue by iocmet** [Col-E/Recaf#590]

**Comment by 1fxe** [comment]
Yes

**Comment by Col-E** [comment]
Assuming you're on 2X:

https://user-images.githubusercontent.com/21371686/185695207-1b1838f6-8790-466f-8015-93a3cc3757fa.mp4

**Comment by Nowilltolife** [comment]
Use table view, also nice portal sound ambiance

**Comment by Col-E** [comment]
3X generally is more clear about _"hey, I don't know what you clicked on, here's why"_. But generally when something like this occurs its because the AST parser we used cannot determine the method descriptor of the method/constructor. This can happen if not all the type information is present and cannot be reconstructed with JPhantom.
