### ISSUE TITLE
Better search function

### ISSUE THREAD

**Issue by 4194304** [Col-E/Recaf#732]
## Better search function

Currently, finding certain things within classes like names, numbers, hexadecimal and other things is near impossible due to the search functionality within Recaf being useful in super specific cases and being able to be used for nothing else other than that. For example, if you want to search for 32000064/16, with strings you'll get nothing relevant, neither values, class references, member references, class declarations, instructions or even CTRL+F on the folder.

The way that the improved search functionality would work is decompiling all the files, then looking through their contents (There's probably a much better method of doing this.) Also another thing that would be nice is the ability to open class files from the search function, rather than having to find each class yourself. An "open all" button would be a good feature to have too, but implement a warning about performance issues if 15 or more classes are being opened at once.

**Comment by Col-E** [comment]
> if you want to search for 32000064/16, with strings you'll get nothing relevant, neither values, class references, member references, class declarations, instructions or even CTRL+F on the folder.

I don't understand what you're trying to get at here.

Are you searching for a hexadecimal number? If so then the value search is what you want. You won't get value results in a strings search. Also, what notation is `Number/Radix`? Use `0xHexNumberHere`

The 3x snapshots support various number formats:

- 849128 int
- 0xCF4E8 int
- 849128L long
- 0xCF4E8L long
- 849128.0 double
- 849128.0D double
- 849128.0F float

> The way that the improved search functionality would work is decompiling all the files

That would be an improvement in only small inputs. This would be terrible for performance in larger or obfuscated samples, and because some obfuscation or even normal jank code can prevent proper decompilations you may miss values with this approach that you would otherwise find will a well-formed search.

> CTRL+F on the folder.

What? 

> Also another thing that would be nice is the ability to open class files from the search function, rather than having to find each class yourself. 

You can do that. Right click the tree results, or press enter on them if you're navigating via keyboard.
