### ISSUE TITLE
Tiny v1 mapping don't work

### ISSUE THREAD

**Issue by sheng-ri** [Col-E/Recaf#764]
**Describe the bug**

We can get tiny map from [here](https://maven.fabricmc.net/net/fabricmc/yarn/)
Tiny Mapping Doesn't work.
In dev4 latest version.

**To Reproduce**

1. Open any fabric mod(1.20.4)
2. Using Mapping->Apply->Tiny-V1
3. Nothing Happened

**Exception**

None

**Screenshots**

None

**Comment by sheng-ri** [comment]
Did I do anything wrong
--
I found tiny format is different in https://github.com/Col-E/Recaf/blob/6060aa032178c304d74c12e11cc25cb331d1675b/recaf-core/src/main/java/software/coley/recaf/services/mapping/format/TinyV1Mappings.java#L21

**Comment by Col-E** [comment]
Accidentally closed, was writing a comment for a separate ticket, oops

**Comment by sheng-ri** [comment]
https://maven.fabricmc.net/net/fabricmc/yarn/1.20.2%2Bbuild.4/yarn-1.20.2%2Bbuild.4-tiny.gz

**Comment by Col-E** [comment]
Looks like the current implementation we have was based on the layout of `v1	intermediary	named` but these are `v1	official	intermediary	named` which results in `official -> intermediary`

**Comment by Col-E** [comment]
Addressed in https://github.com/Col-E/Recaf/commit/0fa355175932b5e19e5ae012cb5b05e63d3a81a3

Be aware that due to the structure of some mixins, not all classes will be renamed since Recaf isn't aware of `@Mixin(TargetClass.class)` implying that `this extends/implements TargetClass`. But that is a separate issue from the format parser.
