### ISSUE TITLE
Recaf deadlock changing recompilation target version from class view popup

### ISSUE THREAD

**Issue by Sukasa** [Col-E/Recaf#798]
**Describe the bug**

When attempting to modify the recompilation target version via the gear menu in the lower-right of the class view, recaf deadlocks.

**To Reproduce**

This reproduction was tested with multiple .jar files and multiple classes within those .jar files.
One thing in common all .jar files had was they were Minecraft 1.7.10 mods.

1. Open workspace.  Reproduction tested with [Railcraft_1.7.10-9.12.2.1.jar.zip](https://github.com/user-attachments/files/15526267/Railcraft_1.7.10-9.12.2.1.jar.zip)
2. Navigate to any class
3. Select gear icon in lower-right of class view
4. Try to change "Compile target version" away from "Match class file version"
5. Recaf deadlocks

**Exception**

No exception is generated.  JStack output attached in lieu.

(Updated, I accidentally JStack'd the launcher and not recaf)
[crash.txt](https://github.com/user-attachments/files/15526355/crash.txt)

**Screenshots**

![image](https://github.com/Col-E/Recaf/assets/1186656/4ab22463-8372-4b8a-880c-116f3b2f4a17)

**Comment by Sukasa** [comment]
In the event that this cannot be reproduced, it may also be related to me having multiple files in the workspace at the same time.  Just in case that's so, this is my current workspace, zipped up
[Recaf Workspace.zip](https://github.com/user-attachments/files/15526358/Recaf.Workspace.zip)

**Comment by Col-E** [comment]
Based on the `JavaFX Application Thread` contents, my best guess is this is some really odd bug caused by the combo-box resizing triggering an infinite scene invalidation loop.

https://github.com/Col-E/Recaf/blob/dev4/recaf-ui/src/main/java/software/coley/recaf/ui/pane/editing/jvm/JvmDecompilerPaneConfigurator.java#L104

In these combo-box classes, can you try adding this to the constructors?
```java
int w = 200;
setMaxWidth(w);
setPrefWidth(w);
```

The idea is that if we force the combo-boxes to be a uniform size, they won't ever resize and get us into this odd state. I cannot seem to reproduce the issue on my end but this is my best guess as to what _should_ fix it.

**Comment by Col-E** [comment]
I added the hypothetical fix in 65a6ccd0f95170efa00b99e7898ce46c060346bf - If this issue persists just re-open this issue.
