### ISSUE TITLE
"Main Window" improvements

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#82]
The following improvements are for the "Main Window"

## Tool tips for icons
The icons should have "tool tips".

## More items for "File" menu
The "File" menu should have a "Open", "Close", "Export", "Save as", "Save", "Exit"

## More items for "Help" menu
The main windows should include a "Help" menu with the traditional items (About, help, contributors, etc)

## Warning in the "Close button"
When the close button is pressed, it should warn the user that all changes will be lost. For example: "Doy you really want to exit? All unsaved changes will be lost."

**Comment by Col-E** [comment]
> Tooltips for icons

:+1: 

> More file menu options

`Open`  - Exists as `Load`, renaming it to `Open` would make sense though.

`Close` - Due to the assumption that the input will never be `null` past startup this would require some cleanup. It can be done but its low on the priority list.

`Export` 

`Save as` - Export is functionally a `Save as`.

`Save` - Export's `Save as` functionality makes this redundant

`Exit` - Fair, I just close it with the `X`, since config is saved in the shutdown hook. Adding the warning you mention to both also makes sense.

> Help menu

:+1: 

> Close button warning

:+1:

**Comment by pedroflor** [comment]
Thanks!
