### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by FukCat** [Col-E/Recaf#830]
## 1Can automatic renaming be added (similar to jadx), but some libraries need to be skipped for renaming; Additionally, there are some issues with the built-in renaming feature of Recaf, as renaming classes to other packages may cause damage
2You can add a button to turn off the error and Java error prompts of the decompiler, because which can cause great trouble for reverse analysis, or you can directly view the bytecode of the entire class
3There is no search option in the table of viewing methods And there is no option to add new classes or files here

**Comment by Col-E** [comment]
> Automatic renaming _(similar to jadx)_

Use the mapping generator feature if you do not like the names of classes & members. There are built-in filters for matching against reserved keywords and bs whitespace names in the same way jadx detects what should be renamed.

But by default I do not want to always apply this renaming since it poses some issues in our UX. For instance, there would be a disconnect of names in items seen in the decompile view and the `fields & methods` tab which would be confusing.

> renaming classes to other packages may cause damage

Provide exact examples with samples, otherwise I cannot address this as the samples I have on hand all work.

> You can add a button to turn off the error and Java error prompts of the decompiler, because which can cause great trouble for reverse analysis

The errors will only show up if you attempt to save/recompile the decompiled code.

> ...  or you can directly view the bytecode of the entire class

Planned, but you can also use the full-class assembler to view our JASM formatted class model.

> There is no search option in the table of viewing methods

Upgrade to 4.X and use the `fields & methods` tab on the top right of any class view. It has search capabilities.

> And there is no option to add new classes or files here

Currently, additional resources can be added to the workspace as read-only data that is used for reference and support for features like recompilation.

Things like creating new classes in the primary resource are planned, we haven't ironed out the desired UX for it yet.

**Comment by Col-E** [comment]
For better tracking, it would be greatly appreciated if you could report issues one at a time so individual features and fixes can be tracked 👍

**Comment by Amejonah1200** [comment]
It would be also nice if the formatting isn't being strange too

**Comment by Col-E** [comment]
For the comments above, I'm going to close this.
