### ISSUE TITLE
Gradle only builds with Java 22, which is EOL

### ISSUE THREAD

**Issue by pluiedev** [Col-E/Recaf#877]
As [this comment in #865](https://github.com/Col-E/Recaf/issues/865#issuecomment-2414355382) pointed out, currently the build script arbitrarily sets the `languageVersion` to only Java 22 and not Java 23, preventing it from building on Java 23. This is especially problematic when working with package libraries like Nixpkgs, which has already removed Java 22 as it has reached its EOL date in [September 2024](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).

Please remove the version specifier, or maybe setting a *minimum* version requirement rather than an exact one.

**Comment by Col-E** [comment]
> which has already removed Java 22 as it has reached its EOL date in September 2024

Would it be reasonable to assume that when Java 23 hits EOL that Nixpkgs will also remove it?

> currently the build script arbitrarily sets the languageVersion to only Java 22

We use 22 _(A non LTS release)_ because:
- The [FFM API](https://openjdk.org/jeps/454) has been moved to a stable API from its incubator state
- JavaFX has plans on bumping its minimum version to 22 to also take advantage of FFM

We use toolchain support to ensure anyone building should get _the same exact output_. I noticed a while ago that Gradle had stopped auto-downloading JDK's for toolchain usage a bit ago and meant to address that by utilizing the [foojay toolchain plugin](https://github.com/gradle/foojay-toolchains) but never really got around to it.

**Comment by pluiedev** [comment]
> Would it be reasonable to assume that when Java 23 hits EOL that Nixpkgs will also remove it?

Yes. As far as I can tell Nixpkgs only supports Java 8, 11, 17, 21 and 23 in the source tree — everything else is flagged as broken and unsupported.

Also, downloading a JDK would also not be ideal for Nixpkgs since build environments are sandboxed and programs do not have internet access. The only reason that Gradle still somehow works is because we use a man-in-the-middle cache which has all dependencies prefetched and locked at specific versions and hashes, and in the build process we hijack any network requests to return dependencies from the cache. Yes, it's janky, but it achieves the same effect of reproducibility.

**Comment by xroberx** [comment]
> We use 22 _(A non LTS release)_ because:
> 
>     * The [FFM API](https://openjdk.org/jeps/454) has been moved to a stable API from its incubator state

So the FFM API is also stable in Java 23, no?

**Comment by Col-E** [comment]
I'm going to keep 22 as the build target for now, but [I have addressed the issues seen when updating it to 23](https://github.com/Col-E/Recaf/commit/4ab6015280426d00fec4af02e454be1512872765).

If you're consuming the repo and doing builds in a 23 environment, find/replace the version to what you want and it should build now.
