### ISSUE TITLE
Support 'Compact Middle Packages' mode in file tree

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#92]
When 'Compact Middle Packages' is off:
![without](https://user-images.githubusercontent.com/12008103/46253310-c72e8800-c4aa-11e8-81f5-98b44f21d7b9.png)
When it's on:
![with](https://user-images.githubusercontent.com/12008103/46253312-ce559600-c4aa-11e8-9c57-d50f2ab425db.png)
![github](https://user-images.githubusercontent.com/12008103/46253317-11b00480-c4ab-11e8-8700-065037671548.png)

It'll make navigating/locating classes in complex file tree a lot easier.

I tried to implement this myself, but turns out it's a lot more difficult than I thought.

**Comment by Col-E** [comment]
> I tried to implement this myself, but turns out it's a lot more difficult than I thought.

Yeah, especially considering the fact that you can rename classes. For example:

* com/package
    * MyClass1
    * MyClass2

Rename `com/package/MyClass1` to  `com/MyClass1` 

* com
    * package
        * MyClass1
    * MyClass2

The merged `com/package` will have to be separated. I've never been super great with tree UI's. Its not something I expect to get done any time soon. 

***

An alternative idea would be to do what [Luyten](https://github.com/deathmarine/Luyten) does. When a package is opened up, children are recursively opened until there are 2 or more children. This doesn't simplify the UI visually, but makes it faster since it reduces the number of clicks required to navigate to some class in a package.
